### ISSUE TITLE
Unmet Dependencies with Latest Spectacle

### ISSUE THREAD

**Issue by backlineint** [FezVrasta/spectacle-image-slide#1]
With a recently installed spectacle project I am unable to install via npm.

npm install --save spectacle-image-slide
my-presentation@0.1.0 /Users/brian/repos/aoty-visualizations/slides
├── UNMET PEER DEPENDENCY react@16.2.0
├── UNMET PEER DEPENDENCY spectacle@^2.0.0
└── spectacle-image-slide@1.0.1 

npm WARN spectacle-image-slide@1.0.1 requires a peer of react@^15.5.4 but none was installed.
npm WARN spectacle-image-slide@1.0.1 requires a peer of spectacle@^2.0.0 but none was installed.

**Comment by FezVrasta** [comment]
Umh you simply need to install the listed dependencies, they are peer dependencies so you must install them directly.
